export const answerType = {
  CREATE_ANSWER: 'CREATE_ANSWER',
  GET_ANSWERS_BY_QUESTION_ID: 'GET_ANSWERS_BY_QUESTION_ID',
  UPDATE_ANSWER: 'UPDATE_ANSWER',
  DELETE_ANSWER: 'DELETE_ANSWER',
  LIKE_OR_UNLIKE_ANSWER: 'LIKE_OR_UNLIKE_ANSWER',
  FILTER_ANSWERS: 'FILTER_ANSWERS',
};
