export const answerType = {
  CREATE_ANSWER: 'CREATE_ANSWER',
  GET_ALL_ANSWERS: 'GET_ALL_ANSWERS',
  UPDATE_ANSWER: 'UPDATE_ANSWER',
  DELETE_ANSWER: 'DELETE_ANSWER',
  LIKE_UNLIKE_ANSWER: 'LIKE_UNLIKE_ANSWER',
};
