export const questionType = {
  CREATE_QUESTION: 'CREATE_QUESTION',
  PAGINATE_QUESTIONS: 'PAGINATE_QUESTIONS',
  GET_QUESTION_BY_ID: 'GET_QUESTION_BY_ID',
  GET_QUESTION_BY_USER_ID: 'GET_QUESTION_BY_USER_ID',
  GET_RECOMMENDATION: 'GET_RECOMMENDATION',
  UPDATE_QUESTION: 'UPDATE_QUESTION',
  DELETE_QUESTION: 'DELETE_QUESTION',
};
